var wvy = wvy || {};
wvy.resources = {
"+add an option": "",
"Add meeting": "",
"Add poll": "",
"Align center": "",
"Align left": "",
"Align right": "",
"and": "",
"are typing": "",
"Are you sure you want to leave this page? There are some unsaved changes.": "",
"Attachment was restored.": "",
"Attachment was trashed.": "",
"Authentication error.": "",
"Browser does not support notifications": "",
"Close": "",
"Comment was restored.": "",
"Comment was trashed.": "",
"Follow": "",
"Following": "",
"Heading 1": "",
"Heading 2": "",
"Heading 3": "",
"Heading 4": "",
"Heading 5": "",
"Heading 6": "",
"Heading 9": "",
"Hide completed": "",
"Insert emoji": "",
"Insert file": "",
"Insert image": "",
"Insert/edit file": "",
"Insert/edit image": "",
"Insert/edit link": "",
"invite": "",
"is typing": "",
"Justify": "",
"Keyboard shortcuts": "",
"Mark as read": "",
"Mark as unread": "",
"Message from": "",
"More": "",
"Normal text": "",
"Please sign in to the meeting provider before you submit the comment!": "",
"Please sign in to the meeting provider before you submit the message!": "",
"Please sign in to the meeting provider before you submit the post!": "",
"Post was restored.": "",
"Post was trashed.": "",
"Reconnecting...": "",
"Reload": "",
"Remove": "",
"Remove format": "",
"Saved": "",
"Saving": "",
"Search...": "",
"Show completed": "",
"Source code": "",
"Star": "",
"Strikethrough": "",
"Submit": "",
"Task details": "",
"Task was restored.": "",
"Task was trashed.": "",
"Teams meeting": "",
"The item was deleted.": "",
"The item was restored.": "",
"The signed in user has changed.": "",
"Toggle bulleted list": "",
"Toggle numbered list": "",
"Toggle toolbar": "",
"Undo": "",
"Unfollow": "",
"Unstar": "",
"User was restored.": "",
"User was trashed.": "",
"What's on your mind?": "",
"You have a new notification": "",
"You have been signed out.": "",
"You have signed in.": "",
"Your comment...": "",
"Zoom meeting": "",
};
